name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker login
      run: Docker login -u="chandan143" -p="chandan12"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag chandan143/awsconfig:$gitsed
    - name: Docker push
      run: Docker push chandan143/awsconfig:$gitsed
